### ISSUE TITLE
Add more info on quickstart doc - deploy-dev.md

### ISSUE THREAD

**Issue by renato-marciano** [Azure-Samples/distributed-az-edge-framework#58]
After running the deploy-az-dev-bootstrapper.ps1 script successfully, I wasn't sure how to verify that everything was successfully deployed and running.

Suggestion to add more sections to the document after deployment.
This could be as simple as screenshots of terminal output after running the script, running 'kubectl get pods' and a sample screenshot of what expected output looks like. Or going to Eventhub that was deployed and verifying that messages are there. 
Also, there was no specific mention of simulator being deployed that continuously runs. It may be good to mention and caution leaving it running.

**Comment by katriendg** [comment]
Great suggestion, we will add some clarity and include a section on cleaning up resources.
